server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
      - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
        #匹配后提供服务的路由地址
        #uri: http://localhost:8001
        uri: lb://CLOUD-PROVIDER-PAYMENT
        predicates:
        - Path=/payment/get/** # 断言，路径相匹配的进行路由
      - id: payment_route2
        #uri: http://localhost:8001
        uri: lb://CLOUD-PROVIDER-PAYMENT
        predicates:
        - Path=/payment/lb/** #断言,路径相匹配的进行路由
        #- After=2020-11-05T10:53:09.452+08:00[Asia/Shanghai] #在这个时间之后才可以调用
        #- Cookie=username,cp #必须匹配对应的cookie才能调用
        #- Header=X-Request-Id,\d+ #两个参数一个属性名称一个正则表达式
        #- Method=GET
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/